name: Tests

on:
  push:
    paths:
      - "public/js/**"
      - "tests/**"
  pull_request:
    paths:
      - "public/js/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun test
